[package]
name = "file_watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
notify = "8.0.0"
pcap = "2.3.0"
pnet = "0.35.0"
regex = "1.11.1"
sha2 = "0.10.9"
sysinfo = "0.36.1"
